apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    name: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: weather-app
  template:
    metadata:
      name: weather-app
      labels:
        name: weather-app
    spec:
      containers:
        - name:  weather-app
          image: vigneshsweekaran/weather-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
