apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weather-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50