apiVersion: v1
kind: Service
metadata:
  name: weather-app
  labels:
    name: weather-app
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: weather-app
  type: LoadBalancer
